name: Manually clear cache
on:
  workflow_dispatch:

jobs:
  cleanup:
    permissions:
      actions: write
    runs-on: ubuntu-slim
    steps:
      - name: Cleanup
        run: |
          echo "Deleting caches..."
          gh cache delete --all --ref $GITHUB_REF --succeed-on-no-caches
          echo "Done"
        env:
          GH_TOKEN: ${{ github.token }}
